# Generated by Django 4.2.3 on 2023-08-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.DeleteModel(
            name='Pagos',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
        migrations.AlterModelOptions(
            name='alumnos',
            options={'ordering': ['apellido'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='maestras',
            options={'ordering': ['apellido'], 'verbose_name': 'Maestra', 'verbose_name_plural': 'Maestras'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'ordering': ['nombre']},
        ),
    ]
