# Generated by Django 4.2.3 on 2023-08-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_eventos_delete_pagos_delete_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
