# Generated by Django 4.2.3 on 2023-08-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_eventos_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'ordering': ['fecha'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
